name: Clojars Deploy

description: Build JAR and Deploy to Clojars

inputs:
  group-id:
    description: Clojars Group ID (defaults to `com.yetanalytics`)
    required: false
    default: 'com.yetanalytics'

  artifact-id:
    description: Clojars Artifact ID (i.e. the name of the lib itself)
    required: true

  src-dir:
    description: The source directory (defaults to `src/main`)
    required: false
    default: 'src/main'

  resource-dir:
    description: The resource directory (defaults to `resources`)
    required: false
    default: 'resources'

  # Passing GH secrets as inputs seems kind of sketch...

  # clojars-username:
  #   description: The Clojars username GH secret
  #   required: true

  # clojars-token:
  #   description: The Clojars access token GH secret
  #   required: true

runs:
  using: "composite"
  steps:
    - name: Add aliases
      shell: bash
      run: >
        clojure -Sdeps
        '{:aliases
           {:build
             {:replace-deps {io.github.seancorfield/build-clj {:git/tag "v0.6.3"
                                                               :git/sha "9b8e09b"}}
              :ns-default build}}}'

    - name: Build JAR file
      shell: bash
      run: >
        clojure -X:build jar
        :lib ${{ inputs.group-id }}/${{ inputs.artifact-id }}
        :version '"${{ github.ref_name }}"'
        :src-dirs '["${{ inputs.src-dir }}"]'
        :resource-dirs '["${{ inputs.resource-dir }}"]'
        :scm '{
          :url "https://github.com/${{ github.repository }}"
          :tag "${{ github.sha }}"
          :connection "scm:git:git://github.com/${{ github.repository }}.git"
          :developerConnection "scm:git:ssh://git@github.com/${{ github.repository }}.git"
        }'

    # This is mainly a debug step that exists to ensure sanity checking
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.artifact-id }}-artifact-${{ github.ref_name }}
        path: target/${{ inputs.artifact-id }}-${{ github.ref_name }}.jar

    # - name: Deploy to Clojars
    #   shell: bash
    #   run: >
    #     clojure -X:build deploy
    #     :lib ${{ inputs.group-id }}/${{ inputs.artifact-id }}
    #     :version "${{ github.ref_name }}"
    #   env:
    #     CLOJARS_USERNAME: ${{ inputs.clojars-username }}
    #     CLOJARS_PASSWORD: ${{ inputs.clojars-token }}
