name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  deploy-clojars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get an env
        uses: yetanalytics/actions/setup-env@v0.0.1
      
      - name: Test deployment
        uses: yetanalytics/actions/deploy-clojars@v0.0.1
        with:
          artifact-id: 'actions'
          version: 'LATEST'
          resource-dirs: '[]'
          # publish: false
          # We're not actually publishing to Clojars so use dummy values
          clojars-username: 'foo'
          clojars-deploy-token: 'bar'

  nvd_scan:
    uses: yetanalytics/actions/.github/workflows/nvd-scan.yml@v0.0.1
